### ISSUE TITLE
License breach warning

### ISSUE THREAD

**Issue by wf9a5m75** [BeMyEye/cordova-plugin-googlemaps#10]
As I written in the LICENSE file of the official repository site, 
- you **CAN** modify or extend forked repository,
- but you **CAN NOT** copy the files or codes from the official repository.

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/LICENSE#L203-L205

You guys still the code and files on this commit.
https://github.com/BeMyEye/cordova-plugin-googlemaps/commit/074b0f8333579a294b4fd1cc7f1d35bafea4e159

Do you want to battle with me at Los Angeles, US?

**Comment by cvaliere** [comment]
Your plugin was under Apache 2 license so your claim appears groundless. If you don't agree please have your lawyer sending a formal claim to BeMyEye Holdings Ltd, 40 Islington High Street, London N1 8XB, United Kingdom
