### ISSUE TITLE
Last license warning

### ISSUE THREAD

**Issue by wf9a5m75** [BeMyEye/cordova-plugin-googlemaps#11]
Since you declined even having a discussion at 
https://github.com/BeMyEye/cordova-plugin-googlemaps/issues/10,
this is the last chance to have a discussion before sending DMCA Takedown requesting.

As I wrote in the LICENSE file of the official repository site,
- you **CAN** modify or extend forked repository,
- but you **CAN NOT** copy the files or codes from the official repository.

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/LICENSE#L203-L205

So if you follow the rules on this conditions, I wont do action at this time.
If you just decline, I submit the DMCA Takedown requesting.

**Comment by wf9a5m75** [comment]
Okay, it seems you are not interested in the discussion.
Since you merged the code to the master, the gate is now closed.
I will send a DMCA takedown request to GitHub.

**Comment by cvaliere** [comment]
Your plugin was under Apache 2 license so your claim appears groundless. If you don't agree please have your lawyer sending a formal claim to BeMyEye Holdings Ltd, 40 Islington High Street, London N1 8XB, United Kingdom
